name: 每日签到

on:
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '30 0 * * *'
  watch:
    types: [ started ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: 'Set up Python'
      uses: actions/setup-python@v1
      with: 
        python-version: 3.7
        
    - name: '安装 requirements'
      run: pip install -r ./requirements.txt
      
    - name: '运行【签到】'
      run: python3 index.py
      env:
          IS_GITHUB : true
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
